INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C0', '16.35', '2109.89')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#0', '17.32', '1991.47')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D0', '18.35', '1879.69')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#0', '19.45', '1774.20')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E0', '20.60', '1674.62')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F0', '21.83', '1580.63')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#0', '23.12', '1491.91')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G0', '24.50', '1408.18')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#0', '25.96', '1329.14')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A0', '27.50', '1254.55')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#0', '29.14', '1184.13')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B0', '30.87', '1117.67')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C1', '32.70', '1054.94')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#1', '34.65', '995.73')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D1', '36.71', '939.85')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#1', '38.89', '887.10')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E1', '41.20', '837.31')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F1', '43.65', '790.31')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#1', '46.25', '745.96')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G1', '49.00', '704.09')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#1', '51.91', '664.57')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A1', '55.00', '627.27')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#1', '58.27', '592.07')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B1', '61.74', '558.84')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C2', '65.41', '527.47')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#2', '69.30', '497.87')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D2', '73.42', '469.92')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#2', '77.78', '443.55')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E2', '82.41', '418.65')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F2', '87.31', '395.16')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#2', '92.50', '372.98')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G2', '98.00', '352.04')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#2', '103.83', '332.29')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A2', '110.00', '313.64')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#2', '116.54', '296.03')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B2', '123.47', '279.42')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C3', '130.81', '263.74')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#3', '138.59', '248.93')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D3', '146.83', '234.96')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#3', '155.56', '221.77')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E3', '164.81', '209.33')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F3', '174.61', '197.58')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#3', '185.00', '186.49')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G3', '196.00', '176.02')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#3', '207.65', '166.14')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A3', '220.00', '156.82')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#3', '233.08', '148.02')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B3', '246.94', '139.71')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C4', '261.63', '131.87')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#4', '277.18', '124.47')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D4', '293.66', '117.48')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#4', '311.13', '110.89')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E4', '329.63', '104.66')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F4', '349.23', '98.79')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#4', '369.99', '93.24')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G4', '392.00', '88.01')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#4', '415.30', '83.07')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A4', '440.00', '78.41')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#4', '466.16', '74.01')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B4', '493.88', '69.85')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C5', '523.25', '65.93')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#5', '554.37', '62.23')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D5', '587.33', '58.74')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#5', '622.25', '55.44')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E5', '659.25', '52.33')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F5', '698.46', '49.39')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#5', '739.99', '46.62')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G5', '783.99', '44.01')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#5', '830.61', '41.54')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A5', '880.00', '39.20')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#5', '932.33', '37.00')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B5', '987.77', '34.93')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C6', '1046.50', '32.97')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#6', '1108.73', '31.12')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D6', '1174.66', '29.37')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#6', '1244.51', '27.72')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E6', '1318.51', '26.17')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F6', '1396.91', '24.70')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#6', '1479.98', '23.31')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G6', '1567.98', '22.00')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#6', '1661.22', '20.77')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A6', '1760.00', '19.60')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#6', '1864.66', '18.50')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B6', '1975.53', '17.46')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C7', '2093.00', '16.48')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#7', '2217.46', '15.56')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D7', '2349.32', '14.69')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#7', '2489.02', '13.86')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E7', '2637.02', '13.08')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F7', '2793.83', '12.35')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#7', '2959.96', '11.66')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G7', '3135.96', '11.00')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#7', '3322.44', '10.38')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A7', '3520.00', '9.80')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#7', '3729.31', '9.25')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B7', '3951.07', '8.73')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C8', '4186.01', '8.24')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('C#8', '4434.92', '7.78')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D8', '4698.63', '7.34')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('D#8', '4978.03', '6.93')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('E8', '5274.04', '6.54')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F8', '5587.65', '6.17')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('F#8', '5919.91', '5.83')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G8', '6271.93', '5.50')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('G#8', '6644.88', '5.19')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A8', '7040.00', '4.90')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('A#8', '7458.62', '4.63')
INSERT INTO Tones (Name, Frequency, WaveLenght) VALUES ('B8', '7902.13', '4.37')

INSERT INTO Tunings (NumberOfStrings, Name) VALUES ('6','Standard E')
INSERT INTO Tunings (NumberOfStrings, Name) VALUES ('6','Standard D')
INSERT INTO Tunings (NumberOfStrings, Name) VALUES ('6','Drop D')
INSERT INTO Tunings (NumberOfStrings, Name) VALUES ('7','Standard B')
INSERT INTO Tunings (NumberOfStrings, Name) VALUES ('7','Drop A')

INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('1','53','1')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('2','48','1')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('3','44','1')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('4','39','1')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('5','34','1')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('6','29','1')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('1','51','2')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('2','46','2')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('3','42','2')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('4','37','2')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('5','32','2')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('6','27','2')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('1','53','3')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('2','48','3')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('3','44','3')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('4','39','3')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('5','34','3')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('6','27','3')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('1','53','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('2','48','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('3','44','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('4','39','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('5','34','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('6','29','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('7','24','4')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('1','53','5')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('2','48','5')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('3','44','5')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('4','39','5')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('5','34','5')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('6','29','5')
INSERT INTO TonesInTunings (Position, ToneId, TuningId) VALUES ('7','22','5')

INSERT INTO Manufacturers (Name) VALUES ('Ernie Ball')
INSERT INTO Manufacturers (Name) VALUES ('D`Addario')
INSERT INTO Manufacturers (Name) VALUES ('Elixir')
INSERT INTO Manufacturers (Name) VALUES ('Fender')
INSERT INTO Manufacturers (Name) VALUES ('Gibson')
INSERT INTO Manufacturers (Name) VALUES ('Mayones')

INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('9','0.00032037193','0','2','300')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('11','0.00047859352','0','2','300')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('16','0.00101272532','0','2','300')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('26','0.00226278303','1','2','300')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('36','0.00427948328','1','2','300')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('46','0.00682460079','1','2','300')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('12','0.00056966915','0','3','360')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('16','0.00101272532','0','3','360')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('24','0.00227867663','0','3','360')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('32','0.00345498093','1','3','360')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('42','0.00576437327','1','3','360')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('52','0.00859128949','1','3','360')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('11','0.00047859352','0','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('14','0.00077539294','0','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('18','0.00128166631','0','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('28','0.00261904948','1','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('38','0.00472718253','1','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('48','0.00738998403','1','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('58','0.01107193974','1','1','120')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('13','0.00066860229','0','2','180')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('17','0.00114326706','0','2','180')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('26','0.00243582674','2','2','180')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('35','0.00452967341','2','2','180')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('45','0.00745587993','2','2','180')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('56','0.01133570191','2','2','180')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('10','0.00039555397','0','1','320')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('14','0.00077539294','0','1','320')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('20','0.00144756683','2','1','320')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('28','0.00285727477','2','1','320')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('40','0.00572580006','2','1','320')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('50','0.00874468943','2','1','320')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('20','0.00020179503','3','2','200')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('32','0.00051680957','3','2','200')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('40','0.00080753728','3','2','200')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('28','0.00187705094','4','2','200')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('35','0.00369070610','4','2','200')
INSERT INTO Strings (Size, SpecificWeight, StringType, ManufacturerId, NumberOfDaysGood) VALUES ('44','0.00625064572','4','2','200')

INSERT INTO StringsSets (Name, NumberOfStrings) VALUES ('D`Addario XTE Nickel 9-46','6')
INSERT INTO StringsSets (Name, NumberOfStrings) VALUES ('Elixir NanoWeb Nickel 12-52','6')
INSERT INTO StringsSets (Name, NumberOfStrings) VALUES ('Ernie Ball Power Slinky 7 Nickel 11-58','7')
INSERT INTO StringsSets (Name, NumberOfStrings) VALUES ('D`Addario 80/20 Bronze 13-56','6')
INSERT INTO StringsSets (Name, NumberOfStrings) VALUES ('Ernie Ball Paradigm Phosphor 10-50','6')
INSERT INTO StringsSets (Name, NumberOfStrings) VALUES ('D`Addario XTE Classical Normal','6')

INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('1','1','1')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('2','1','2')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('3','1','3')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('4','1','4')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('5','1','5')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('6','1','6')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('7','2','1')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('8','2','2')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('9','2','3')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('10','2','4')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('11','2','5')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('12','2','6')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('13','3','1')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('14','3','2')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('15','3','3')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('16','3','4')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('17','3','5')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('18','3','6')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('19','3','7')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('20','4','1')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('21','4','2')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('22','4','3')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('23','4','4')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('24','4','5')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('25','4','6')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('26','5','1')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('27','5','2')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('28','5','3')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('29','5','4')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('30','5','5')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('31','5','6')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('32','6','1')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('33','6','2')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('34','6','3')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('35','6','4')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('36','6','5')
INSERT INTO StringsInSets (StringId, StringsSetId, Position) VALUES ('37','6','6')

INSERT INTO Instruments (ScaleLenghtBass, ScaleLenghtTreble, NumberOfStrings, ManufacturerId, Model) VALUES ('647','647','6', '4', 'Stratocaster')
INSERT INTO Instruments (ScaleLenghtBass, ScaleLenghtTreble, NumberOfStrings, ManufacturerId, Model) VALUES ('628','628','6', '5', 'Les Paul')
INSERT INTO Instruments (ScaleLenghtBass, ScaleLenghtTreble, NumberOfStrings, ManufacturerId, Model) VALUES ('687','645','7', '6', 'Duvell Elite V-Frets')

INSERT INTO Users (PlayStyle, AccountType, DailyMaintanance, Email, Username, Password) VALUES ('0','1','1', 'testAdminEmail', 'testAdmin', '7ctgYaP9ySyZor1UNHJVMC48sr5B7J5F7yX3PT/Pot0=')
INSERT INTO Users (PlayStyle, AccountType, DailyMaintanance, Email, Username, Password) VALUES ('1','0','3', 'testUserEmail', 'testUser', 'pZwdQFRFP8pAoVczHMP5Zuv9EdI1n2wgLtDxfbIlFEA=')

INSERT INTO MyInstruments (LastStringChange, LastDeepCleaning, GuitarPlace, InstrumentId, HoursPlayedWeekly, NeededLuthierVisit, NextStringChange, NextDeepCleaning, OwnName, UserId) VALUES ('2021-3-11','2021-3-11','0', '1', '30', '1', '2021-9-3', '2021-12-25', 'Strato', '2')
INSERT INTO MyInstruments (LastStringChange, LastDeepCleaning, GuitarPlace, InstrumentId, HoursPlayedWeekly, NeededLuthierVisit, NextStringChange, NextDeepCleaning, OwnName, UserId) VALUES ('2021-8-14','2021-5-11','1', '3', '20', '0', '2022-4-16', '2022-5-11', 'Mayo', '2')
INSERT INTO MyInstruments (LastStringChange, LastDeepCleaning, GuitarPlace, InstrumentId, HoursPlayedWeekly, NeededLuthierVisit, NextStringChange, NextDeepCleaning, UserId) VALUES ('2021-2-13','2021-2-13','0', '2', '5', '0', '2021-4-1', '2021-5-25', '1')

INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('1', '1', '1', '53')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('2', '1', '2', '48')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('3', '1', '3', '44')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('4', '1', '4', '39')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('5', '1', '5', '34')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('6', '1', '6', '29')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('13', '2', '1', '53')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('14', '2', '2', '48')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('15', '2', '3', '44')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('16', '2', '4', '39')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('17', '2', '5', '34')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('18', '2', '6', '29')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('19', '2', '7', '22')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('1', '3', '1', '53')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('2', '3', '2', '48')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('3', '3', '3', '44')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('4', '3', '4', '39')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('5', '3', '5', '34')
INSERT INTO InstalledStrings (StringId, MyInstrumentId, Position, ToneId) VALUES ('6', '3', '6', '27')